# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1af35debeae66b58817ef85c9b7e8c92b211a2c4fa539c66d408af88b20c1add112a55faf4bf6504389bdef18a816702fe73a89662c8c0bdebdf05fd27724271

test:
  secret_key_base: 7cb4e78ce14c67e6d721e4ba58fcf0f4d243192ba97b1c50f2d64fa588ab482d3f7360c4d96aaffa33618d6d3cb65719270db7f0a9eea257fbe54c6c015050aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
